# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment_time']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
    ]
